# Generated by Django 3.2.20 on 2023-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
