# Generated by Django 3.2.20 on 2023-08-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='album',
        ),
    ]
