# Generated by Django 3.2.20 on 2023-08-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20230814_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image_file', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='images',
        ),
    ]
