# Generated by Django 3.2.20 on 2023-08-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20230814_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='count_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('count', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('image_file', models.ImageField(null=True, upload_to='results/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
